training_data_paths:
# - "/home/ubuntu/tsmixup-data.arrow"
#- "./data/bitcoin-train.arrow"
- "/content/chronos-forecasting/arrow_data/open.arrow"
probability:
- 0.9
#- 0.1
lora: false
context_length: 512
prediction_length: 64
min_past: 60
max_steps: 200_000
save_steps: 100_000
log_steps: 500
per_device_train_batch_size: 32
learning_rate: 0.001
optim: adamw_torch_fused
num_samples: 10 #20
shuffle_buffer_length: 100_000
gradient_accumulation_steps: 1
model_id: amazon/chronos-t5-tiny
model_type: seq2seq
random_init: false
tie_embeddings: true
output_dir: ./output/
tf32: true
torch_compile: false #true
tokenizer_class: "MeanScaleUniformBins"
tokenizer_kwargs:
  low_limit: -15.0
  high_limit: 15.0
n_tokens: 4096
lr_scheduler_type: linear
warmup_ratio: 0.0
dataloader_num_workers: 1
max_missing_prop: 0.9
use_eos_token: true
